name: 'Deploy Production'
on:
  push:
    branches:
      - production
env:
  NODE_ENV: production
  BASE_URL: https://jmath.dev
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
jobs:
  buildAndDeploy:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: yarn install --production false
      - run: yarn build
      - run: yarn deploy
